AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Metrics/AbcSize:
  Max: 26

# DSLs inheritly uses long blocks, like describe and contexts in RSpec,
# therefore disable this rule for specs and for the gemspec file
Metrics/BlockLength:
  Exclude:
  - rails_cursor_pagination.gemspec
  - spec/**/*

Metrics/ClassLength:
  Max: 139

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 25

Metrics/ParameterLists:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 13

Layout/LineLength:
  Max: 80

Naming/VariableNumber:
  EnforcedStyle: snake_case

# In Ruby 3.0 interpolated strings will no longer be frozen automatically, so
# to ensure consistent performance, we have to manually call `String#freeze` in
# some places.
Style/RedundantFreeze:
  Enabled: false
